-- govshop schema (MySQL 8.0+)
-- Charset for Korean text
CREATE DATABASE IF NOT EXISTS govshop
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_0900_ai_ci;
USE govshop;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- USER
CREATE TABLE IF NOT EXISTS user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('ELDER','GUARDIAN','ADMIN') NOT NULL,
  phone VARCHAR(20),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- GUARDIAN LINK
CREATE TABLE IF NOT EXISTS guardian_link (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  elder_id BIGINT NOT NULL,
  guardian_id BIGINT NOT NULL,
  status ENUM('REQUESTED','APPROVED','REJECTED') NOT NULL DEFAULT 'REQUESTED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_elder_guardian (elder_id, guardian_id),
  CONSTRAINT fk_gl_elder FOREIGN KEY (elder_id) REFERENCES user(id) ON DELETE CASCADE,
  CONSTRAINT fk_gl_guardian FOREIGN KEY (guardian_id) REFERENCES user(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- GUARDIAN POLICY
CREATE TABLE IF NOT EXISTS guardian_policy (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  guardian_id BIGINT NOT NULL,
  spending_limit DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  approval_mode ENUM('AUTO','MANUAL') NOT NULL DEFAULT 'MANUAL',
  notify_channel ENUM('SMS','PUSH') NOT NULL DEFAULT 'SMS',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_gp_guardian FOREIGN KEY (guardian_id) REFERENCES user(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_gp_guardian ON guardian_policy(guardian_id);

-- CATEGORY
CREATE TABLE IF NOT EXISTS category (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  parent_id BIGINT NULL,
  depth INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES category(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_category_parent ON category(parent_id);

-- PRODUCT
CREATE TABLE IF NOT EXISTS product (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  category_id BIGINT NOT NULL,
  name VARCHAR(500) NOT NULL,
  brand VARCHAR(255),
  unit VARCHAR(50),
  origin VARCHAR(100),
  price DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  stock INT UNSIGNED NOT NULL DEFAULT 0,
  rating DECIMAL(3,2) DEFAULT 0.00 CHECK (rating >= 0.00 AND rating <= 5.00),
  image_url VARCHAR(1000),
  spec_doc_url TEXT,
  description TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_product_category ON product(category_id);
CREATE INDEX idx_product_name ON product(name);

-- ADDRESS (배송지)
CREATE TABLE IF NOT EXISTS address (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  receiver_name VARCHAR(100) NOT NULL,
  phone VARCHAR(20),
  zipcode VARCHAR(20),
  addr1 VARCHAR(255),
  addr2 VARCHAR(255),
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_address_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_address_user ON address(user_id);

-- ORDERS
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  address_id BIGINT NULL,
  total_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  status ENUM('REQUESTED','AWAITING_APPROVAL','APPROVED','PAID','CANCELLED','FAILED') NOT NULL DEFAULT 'REQUESTED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES user(id),
  CONSTRAINT fk_orders_address FOREIGN KEY (address_id) REFERENCES address(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_orders_user ON orders(user_id);
CREATE INDEX idx_orders_created ON orders(created_at);

-- ORDER ITEM
CREATE TABLE IF NOT EXISTS order_item (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
  unit_price DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  subtotal DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  CONSTRAINT fk_oi_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_oi_product FOREIGN KEY (product_id) REFERENCES product(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_oi_order ON order_item(order_id);
CREATE INDEX idx_oi_product ON order_item(product_id);

-- APPROVAL REQUEST (보호자 승인 요청)
CREATE TABLE IF NOT EXISTS approval_request (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT NOT NULL,
  guardian_id BIGINT NOT NULL,
  status ENUM('WAITING','APPROVED','REJECTED','EXPIRED','CANCELLED') NOT NULL DEFAULT 'WAITING',
  request_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  response_time DATETIME NULL,
  reason VARCHAR(500) NULL,
  CONSTRAINT fk_ar_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_ar_guardian FOREIGN KEY (guardian_id) REFERENCES user(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_ar_guardian_status ON approval_request(guardian_id, status);

-- PAYMENT
CREATE TABLE IF NOT EXISTS payment (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT NOT NULL,
  approval_request_id BIGINT NULL,
  amount DECIMAL(15,2) NOT NULL,
  status ENUM('PENDING','SUCCESS','FAILED') NOT NULL DEFAULT 'PENDING',
  payment_method ENUM('MOCK','CARD','BANK') NOT NULL DEFAULT 'MOCK',
  approved_by BIGINT NULL, -- user.id (guardian or system user)
  approved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_payment_approval FOREIGN KEY (approval_request_id) REFERENCES approval_request(id) ON DELETE SET NULL,
  CONSTRAINT fk_payment_approved_by FOREIGN KEY (approved_by) REFERENCES user(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_payment_status ON payment(status);

-- NOTIFICATION
CREATE TABLE IF NOT EXISTS notification (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  type VARCHAR(50) NOT NULL,
  title VARCHAR(255) NULL,
  message TEXT,
  channel ENUM('SMS','PUSH','EMAIL') NOT NULL DEFAULT 'PUSH',
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  read_at DATETIME NULL,
  CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_notif_user ON notification(user_id, is_read);

-- VOICE COMMAND
CREATE TABLE IF NOT EXISTS voice_command (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  command_text VARCHAR(500) NOT NULL,
  result_action ENUM('SEARCH','ADD_CART','BUY','LOGIN','FAIL') NOT NULL,
  success BOOLEAN NOT NULL DEFAULT FALSE,
  confidence DECIMAL(4,3) NULL,
  locale VARCHAR(10) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vc_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_vc_user_created ON voice_command(user_id, created_at);

-- USER EVENT
CREATE TABLE IF NOT EXISTS user_event (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NULL,
  product_id BIGINT NULL,
  order_id BIGINT NULL,
  event_type ENUM('VIEW','SEARCH','CLICK','ADD_TO_CART','PURCHASE') NOT NULL,
  session_id VARCHAR(64) NULL,
  metadata JSON NULL,
  ts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ue_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE SET NULL,
  CONSTRAINT fk_ue_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE SET NULL,
  CONSTRAINT fk_ue_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_ue_user_ts ON user_event(user_id, ts);
CREATE INDEX idx_ue_type_ts ON user_event(event_type, ts);

-- SHIPMENT (배송)
CREATE TABLE IF NOT EXISTS shipment (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT NOT NULL,
  carrier VARCHAR(100),
  tracking_no VARCHAR(100),
  status ENUM('READY','SHIPPED','DELIVERED','RETURNED','CANCELLED') NOT NULL DEFAULT 'READY',
  shipped_at DATETIME NULL,
  delivered_at DATETIME NULL,
  CONSTRAINT fk_ship_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- REVIEW
CREATE TABLE IF NOT EXISTS review (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_item_id BIGINT NOT NULL,
  rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_review_oi FOREIGN KEY (order_item_id) REFERENCES order_item(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;